def main():
    try:
        
        return True
    except Exception as e:
        print(f"Error: {e} \nin main")
        return False